spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: em_test
    password: em_123456
    url: jdbc:mysql://127.0.0.1:3306/springboot_api_seed?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowMultiQueries=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      connection-test-query: SELECT 1
      max-lifetime: 1800000
      connection-timeout: 30000
      pool-name: Hikaricp-pool

mybatis-plus:
  configuration:
    # 生产环境关闭SQL日志的打印
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl

logging:
  file:
    path: /var/log/${spring.application.name}